import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig } from '../../../../schemas';

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

// Design System Constants
const COLORS = {
  primary: { r: 0, g: 31, b: 63 },        // Navy Blue
  secondary: { r: 41, g: 128, b: 185 },   // Light Blue
  success: { r: 82, g: 196, b: 26 },      // Green
  warning: { r: 250, g: 173, b: 20 },     // Orange
  danger: { r: 255, g: 77, b: 79 },       // Red
  gray: { r: 189, g: 189, b: 189 },       // Gray
  lightGray: { r: 245, g: 245, b: 245 },  // Light Gray
  white: { r: 255, g: 255, b: 255 },      // White
  text: { r: 0, g: 0, b: 0 },             // Black
  textSecondary: { r: 128, g: 128, b: 128 }, // Gray Text
};

const SPACING = {
  page: {
    top: 20,
    left: 15,
    right: 15,
  },
  section: 12,
};

const FONTS = {
  title: { size: 24, style: 'bold' },
  heading: { size: 12, style: 'bold' },
  subheading: { size: 10, style: 'bold' },
  body: { size: 9, style: 'normal' },
  small: { size: 8, style: 'normal' },
  tiny: { size: 7, style: 'normal' },
};

export const generateComplianceReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF();
  const reportId = `COMP-${Date.now()}`;
  let yPos = SPACING.page.top;

  // Professional Header (50mm height with accent line)
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  doc.rect(0, 0, 210, 50, 'F');
  
  // Report title
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b);
  doc.setFontSize(FONTS.title.size);
  doc.setFont('helvetica', FONTS.title.style);
  doc.text('📋 Compliance Report', 105, 20, { align: 'center' });
  
  // Subtitle
  doc.setFontSize(FONTS.heading.size);
  doc.setFont('helvetica', FONTS.body.style);
  doc.text(config.title || 'Water Quality Standards Compliance Analysis', 105, 30, { align: 'center' });
  
  // Report ID
  doc.setFontSize(FONTS.small.size);
  doc.text(`Report ID: ${reportId}`, 105, 38, { align: 'center' });
  
  // Accent line (secondary color)
  doc.setFillColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
  doc.rect(0, 50, 210, 2, 'F');

  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  yPos = 60;

  // Information Card (rounded rectangle with metadata)
  const cardHeight = 22;
  doc.setFillColor(COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b);
  doc.roundedRect(SPACING.page.left, yPos, 180, cardHeight, 2, 2, 'F');
  doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
  doc.setLineWidth(0.3);
  doc.roundedRect(SPACING.page.left, yPos, 180, cardHeight, 2, 2, 'S');
  
  // Two-column layout in card
  const leftColX = SPACING.page.left + 5;
  const rightColX = 105;
  let cardYPos = yPos + 6;
  
  doc.setFontSize(FONTS.small.size);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(COLORS.textSecondary.r, COLORS.textSecondary.g, COLORS.textSecondary.b);
  
  // Left column
  doc.text('Generated:', leftColX, cardYPos);
  doc.setFont('helvetica', FONTS.body.style);
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  doc.text(dayjs().format('MMM D, YYYY'), leftColX + 22, cardYPos);
  
  cardYPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(COLORS.textSecondary.r, COLORS.textSecondary.g, COLORS.textSecondary.b);
  doc.text('Period:', leftColX, cardYPos);
  doc.setFont('helvetica', FONTS.body.style);
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  const period = reportData.period || `${dayjs(config.dateRange?.start).format('MMM D')} - ${dayjs(config.dateRange?.end).format('MMM D, YYYY')}`;
  doc.text(period, leftColX + 22, cardYPos);
  
  // Right column
  cardYPos = yPos + 6;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(COLORS.textSecondary.r, COLORS.textSecondary.g, COLORS.textSecondary.b);
  doc.text('Generated By:', rightColX, cardYPos);
  doc.setFont('helvetica', FONTS.body.style);
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  doc.text(config.generatedBy, rightColX + 28, cardYPos);
  
  cardYPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(COLORS.textSecondary.r, COLORS.textSecondary.g, COLORS.textSecondary.b);
  doc.text('Devices:', rightColX, cardYPos);
  doc.setFont('helvetica', FONTS.body.style);
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  doc.text(reportData.devices?.length?.toString() || config.deviceIds?.length?.toString() || 'All', rightColX + 28, cardYPos);
  
  yPos += cardHeight + SPACING.section;

  // Standards Reference Section
  if (reportData.standards) {
    // Section header with decorative underline
    doc.setFontSize(FONTS.heading.size);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
    doc.text('📜 Regulatory Standards', SPACING.page.left, yPos);
    yPos += 2;
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos, SPACING.page.left + 50, yPos);
    yPos += 8;

    const standards = reportData.standards;
    
    // Standards table
    const standardsData = [
      ['💧 Turbidity', standards.turbidity || '< 5 NTU', 'WHO Guidelines'],
      ['⚗️ TDS', standards.tds || '< 500 ppm', 'WHO Guidelines'],
      ['🔬 pH', standards.ph || '6.5 - 8.5', 'WHO Guidelines'],
    ];
    
    autoTable(doc, {
      startY: yPos,
      head: [['Parameter', 'Standard Limit', 'Reference']],
      body: standardsData,
      styles: { 
        fontSize: FONTS.body.size,
        cellPadding: 3,
        lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
        lineWidth: 0.1,
      },
      headStyles: { 
        fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
        textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
        fontStyle: 'bold',
      },
      alternateRowStyles: { 
        fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b]
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 40 },
        1: { cellWidth: 35 },
      },
      margin: { left: SPACING.page.left, right: SPACING.page.right },
    });
    
    yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
    yPos += SPACING.section;
  }

  // Compliance Summary Badge
  if (reportData.summary) {
    // Section header
    doc.setFontSize(FONTS.heading.size);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
    doc.text('📊 Compliance Summary', SPACING.page.left, yPos);
    yPos += 2;
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos, SPACING.page.left + 50, yPos);
    yPos += 8;

    const summary = reportData.summary;
    
    // Parse compliance rate to determine color
    const complianceRateStr = summary.complianceRate || '0%';
    const complianceRate = parseFloat(complianceRateStr.replace('%', ''));
    let badgeColor = COLORS.danger;
    let badgeLabel = 'Non-Compliant';
    
    if (complianceRate >= 90) {
      badgeColor = COLORS.success;
      badgeLabel = 'Excellent Compliance';
    } else if (complianceRate >= 70) {
      badgeColor = COLORS.warning;
      badgeLabel = 'Moderate Compliance';
    }
    
    // Compliance badge (30mm height)
    const badgeHeight = 30;
    doc.setFillColor(badgeColor.r, badgeColor.g, badgeColor.b);
    doc.roundedRect(SPACING.page.left, yPos, 180, badgeHeight, 2, 2, 'F');
    
    // Badge content (white text)
    doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b);
    doc.setFontSize(FONTS.subheading.size);
    doc.setFont('helvetica', 'bold');
    doc.text(badgeLabel, SPACING.page.left + 5, yPos + 8);
    
    // Compliance details in badge
    doc.setFontSize(FONTS.body.size);
    doc.setFont('helvetica', FONTS.body.style);
    doc.text(`• Total Devices: ${summary.totalDevices || 'N/A'}`, SPACING.page.left + 5, yPos + 15);
    doc.text(`• Compliant Devices: ${summary.compliantDevices || 'N/A'}`, SPACING.page.left + 5, yPos + 21);
    doc.text(`• Compliance Rate: ${complianceRateStr}`, SPACING.page.left + 5, yPos + 27);
    
    yPos += badgeHeight + SPACING.section;
  }

  // Device Compliance Details
  if (reportData.devices && reportData.devices.length > 0) {
    // Section header
    doc.setFontSize(FONTS.heading.size);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
    doc.text('🔍 Device Compliance Details', SPACING.page.left, yPos);
    yPos += 2;
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos, SPACING.page.left + 60, yPos);
    yPos += 10;

    for (const deviceCompliance of reportData.devices) {
      // Check page break (leave space for device header + table)
      if (yPos > 220) {
        doc.addPage();
        yPos = SPACING.page.top;
      }

      // Device header card (light gray background)
      const deviceHeaderHeight = 10;
      doc.setFillColor(COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b);
      doc.roundedRect(SPACING.page.left, yPos, 180, deviceHeaderHeight, 2, 2, 'F');
      doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
      doc.setLineWidth(0.2);
      doc.roundedRect(SPACING.page.left, yPos, 180, deviceHeaderHeight, 2, 2, 'S');
      
      // Device name in header
      doc.setFontSize(FONTS.subheading.size);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
      doc.text(`📟 ${deviceCompliance.deviceName || deviceCompliance.deviceId}`, SPACING.page.left + 3, yPos + 6.5);
      
      yPos += deviceHeaderHeight + 3;

      if (deviceCompliance.complianceStatus) {
        // Map compliance data with emojis
        const complianceData = deviceCompliance.complianceStatus.map((status: any) => {
          const paramEmoji = status.parameter === 'Turbidity' ? '💧' : 
                           status.parameter === 'TDS' ? '⚗️' : 
                           status.parameter === 'pH' ? '🔬' : '📊';
          return [
            `${paramEmoji} ${status.parameter || 'N/A'}`,
            status.value?.toFixed(2) || 'N/A',
            status.standard?.toString() || 'N/A',
            status.status?.toUpperCase() || 'UNKNOWN',
            `${status.percentage?.toFixed(1) || '0'}%`
          ];
        });

        autoTable(doc, {
          startY: yPos,
          head: [['Parameter', 'Value', 'Standard', 'Status', 'Compliance %']],
          body: complianceData,
          styles: { 
            fontSize: FONTS.small.size,
            cellPadding: 2.5,
            lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
            lineWidth: 0.1,
          },
          headStyles: { 
            fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
            textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
            fontSize: FONTS.body.size,
            fontStyle: 'bold',
          },
          alternateRowStyles: { 
            fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b]
          },
          columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 40 },
            1: { cellWidth: 22 },
            2: { cellWidth: 28 },
            3: { fontStyle: 'bold', cellWidth: 28 },
            4: { cellWidth: 25 },
          },
          didParseCell: function(data: any) {
            // Color-code Status column
            if (data.column.index === 3) {
              const status = data.cell.raw.toLowerCase();
              if (status === 'compliant') {
                data.cell.styles.textColor = [COLORS.success.r, COLORS.success.g, COLORS.success.b];
              } else {
                data.cell.styles.textColor = [COLORS.danger.r, COLORS.danger.g, COLORS.danger.b];
              }
            }
            // Color-code Compliance % column
            if (data.column.index === 4) {
              const percentage = parseFloat(data.cell.raw.replace('%', ''));
              if (percentage >= 90) {
                data.cell.styles.textColor = [COLORS.success.r, COLORS.success.g, COLORS.success.b];
              } else if (percentage >= 70) {
                data.cell.styles.textColor = [COLORS.warning.r, COLORS.warning.g, COLORS.warning.b];
              } else {
                data.cell.styles.textColor = [COLORS.danger.r, COLORS.danger.g, COLORS.danger.b];
              }
            }
          },
          margin: { left: SPACING.page.left, right: SPACING.page.right },
        });

        yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 8;
        yPos += 6; // Space between devices
      }
    }
  }

  // Professional footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer separator line
    doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
    doc.setLineWidth(0.5);
    doc.line(SPACING.page.left, 280, 195, 280);
    
    // Page numbers (centered)
    doc.setFontSize(FONTS.small.size);
    doc.setTextColor(COLORS.textSecondary.r, COLORS.textSecondary.g, COLORS.textSecondary.b);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    
    // Copyright and Report ID (centered)
    doc.setFontSize(FONTS.tiny.size);
    doc.text(
      `© ${dayjs().format('YYYY')} IoT Water Quality Monitoring System | Report ID: ${reportId}`,
      105,
      289,
      { align: 'center' }
    );
    
    // Generation timestamp (centered)
    doc.text(
      `Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`,
      105,
      293,
      { align: 'center' }
    );
  }

  return doc;
};
