import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig } from '../../../../schemas';

// ============================================================================
// CONSTANTS - Design System
// ============================================================================
const COLORS = {
  primary: { r: 0, g: 31, b: 63 },
  secondary: { r: 41, g: 128, b: 185 },
  success: { r: 82, g: 196, b: 26 },
  warning: { r: 250, g: 173, b: 20 },
  danger: { r: 255, g: 77, b: 79 },
  gray: { r: 128, g: 128, b: 128 },
  lightGray: { r: 245, g: 245, b: 245 },
  white: { r: 255, g: 255, b: 255 },
  text: { r: 51, g: 51, b: 51 },
};

const SPACING = {
  page: { top: 20, bottom: 25, left: 15, right: 15 },
  section: 12,
  paragraph: 6,
};

const FONTS = {
  title: { size: 24, style: 'bold' },
  subtitle: { size: 14, style: 'normal' },
  heading: { size: 12, style: 'bold' },
  subheading: { size: 10, style: 'bold' },
  body: { size: 9, style: 'normal' },
  small: { size: 8, style: 'normal' },
  tiny: { size: 7, style: 'normal' },
};

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

export const generateDeviceStatusReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  const reportId = `DSR-${dayjs().format('YYYYMMDD')}-${Math.random().toString(36).substr(2, 6).toUpperCase()}`;
  let yPos = 0;

  // ============================================================================
  // HEADER - Professional Design
  // ============================================================================
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  doc.rect(0, 0, 210, 50, 'F');
  
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b);
  doc.setFont('helvetica', FONTS.title.style);
  doc.setFontSize(FONTS.title.size);
  doc.text('Device Status Report', 105, 22, { align: 'center' });
  
  doc.setFont('helvetica', FONTS.subtitle.style);
  doc.setFontSize(FONTS.subtitle.size);
  doc.text(config.title, 105, 32, { align: 'center' });
  
  doc.setFont('helvetica', FONTS.small.style);
  doc.setFontSize(FONTS.small.size);
  doc.text(`Report ID: ${reportId}`, 105, 42, { align: 'center' });

  // Accent line
  doc.setFillColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
  doc.rect(0, 50, 210, 2, 'F');

  yPos = 60;

  // ============================================================================
  // REPORT INFORMATION CARD
  // ============================================================================
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  
  doc.setFillColor(COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b);
  doc.roundedRect(SPACING.page.left, yPos, 180, 18, 2, 2, 'F');
  
  doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
  doc.setLineWidth(0.3);
  doc.roundedRect(SPACING.page.left, yPos, 180, 18, 2, 2, 'S');
  
  yPos += 7;
  
  doc.setFont('helvetica', FONTS.subheading.style);
  doc.setFontSize(FONTS.subheading.size);
  doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  doc.text('Report Information', SPACING.page.left + 5, yPos);
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  yPos += 7;

  doc.setFont('helvetica', FONTS.body.style);
  doc.setFontSize(FONTS.body.size);
  
  doc.text(`Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`, SPACING.page.left + 5, yPos);
  doc.text(`Generated By: ${config.generatedBy}`, 110, yPos);
  
  yPos += 10;

  // ============================================================================
  // SYSTEM OVERVIEW - Status Summary with Health Score
  // ============================================================================
  if (reportData.summary) {
    doc.setFont('helvetica', FONTS.heading.style);
    doc.setFontSize(FONTS.heading.size);
    doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.text('System Overview', SPACING.page.left, yPos);
    
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos + 2, SPACING.page.left + 40, yPos + 2);
    
    yPos += 10;

    const summary = reportData.summary;
    
    // Health Score Badge
    const healthScore = summary.healthScore || 0;
    const healthColor = healthScore >= 80 ? COLORS.success : 
                       healthScore >= 60 ? COLORS.warning : COLORS.danger;
    
    doc.setFillColor(healthColor.r, healthColor.g, healthColor.b);
    doc.roundedRect(SPACING.page.left, yPos, 180, 25, 3, 3, 'F');
    
    doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b);
    doc.setFont('helvetica', FONTS.subheading.style);
    doc.setFontSize(FONTS.subheading.size);
    doc.text(`System Health Score: ${healthScore}%`, SPACING.page.left + 5, yPos + 8);
    
    doc.setFont('helvetica', FONTS.body.style);
    doc.setFontSize(FONTS.body.size);
    doc.text(`Total Devices Monitored: ${summary.totalDevices || 0}`, SPACING.page.left + 5, yPos + 16);
    
    yPos += 30;

    // Status Breakdown Table
    if (summary.statusBreakdown) {
      doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
      doc.setFont('helvetica', FONTS.subheading.style);
      doc.setFontSize(FONTS.subheading.size);
      doc.text('Device Status Breakdown', SPACING.page.left, yPos);
      yPos += 7;

      autoTable(doc, {
        startY: yPos,
        head: [['Status', 'Count', 'Percentage']],
        body: [
          ['🟢 Online', summary.statusBreakdown.online?.toString() || '0', `${summary.statusBreakdown.online || 0}%`],
          ['⚫ Offline', summary.statusBreakdown.offline?.toString() || '0', `${summary.statusBreakdown.offline || 0}%`],
          ['🔴 Error', summary.statusBreakdown.error?.toString() || '0', `${summary.statusBreakdown.error || 0}%`],
          ['🔧 Maintenance', summary.statusBreakdown.maintenance?.toString() || '0', `${summary.statusBreakdown.maintenance || 0}%`],
        ],
        styles: { 
          fontSize: FONTS.body.size, 
          cellPadding: 3,
          lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
          lineWidth: 0.1,
        },
        headStyles: { 
          fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
          textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
          fontStyle: 'bold',
        },
        alternateRowStyles: { 
          fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b] 
        },
        margin: { left: SPACING.page.left, right: SPACING.page.right },
      });

      yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
      yPos += 10;
    }
  }

  // ============================================================================
  // DEVICE DETAILS TABLE
  // ============================================================================
  if (reportData.devices && reportData.devices.length > 0) {
    if (yPos > 220) {
      doc.addPage();
      yPos = SPACING.page.top;
    }

    doc.setFont('helvetica', FONTS.heading.style);
    doc.setFontSize(FONTS.heading.size);
    doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.text('Device Details', SPACING.page.left, yPos);
    
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos + 2, SPACING.page.left + 35, yPos + 2);
    
    yPos += 10;

    const deviceData = reportData.devices.map((device: any) => [
      device.deviceId || 'N/A',
      device.name || device.deviceName || 'Unnamed',
      device.type || 'Sensor',
      device.status?.toUpperCase() || 'UNKNOWN',
      device.firmwareVersion || 'N/A',
      device.lastSeen ? dayjs(device.lastSeen).format('MMM D, HH:mm') : 'Never',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Device ID', 'Name', 'Type', 'Status', 'Firmware', 'Last Seen']],
      body: deviceData,
      styles: { 
        fontSize: FONTS.small.size, 
        cellPadding: 2.5,
        lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
        lineWidth: 0.1,
      },
      headStyles: { 
        fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
        textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
        fontSize: FONTS.body.size,
        fontStyle: 'bold',
      },
      alternateRowStyles: { 
        fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b] 
      },
      columnStyles: {
        0: { cellWidth: 28 },
        3: { fontStyle: 'bold', cellWidth: 20 },
        4: { cellWidth: 22 },
        5: { cellWidth: 25 },
      },
      didParseCell: function(data: any) {
        if (data.column.index === 3) {
          const status = data.cell.raw.toLowerCase();
          if (status === 'online') {
            data.cell.styles.textColor = [COLORS.success.r, COLORS.success.g, COLORS.success.b];
          } else if (status === 'offline') {
            data.cell.styles.textColor = [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b];
          } else if (status === 'maintenance') {
            data.cell.styles.textColor = [COLORS.warning.r, COLORS.warning.g, COLORS.warning.b];
          } else {
            data.cell.styles.textColor = [COLORS.danger.r, COLORS.danger.g, COLORS.danger.b];
          }
        }
      },
      margin: { left: SPACING.page.left, right: SPACING.page.right },
    });
  }

  // ============================================================================
  // PROFESSIONAL FOOTER
  // ============================================================================
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
    doc.setLineWidth(0.5);
    doc.line(SPACING.page.left, 280, 195, 280);
    
    doc.setFont('helvetica', FONTS.small.style);
    doc.setFontSize(FONTS.small.size);
    doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    
    doc.setFontSize(FONTS.tiny.size);
    doc.text(
      `IoT Device Management System © ${dayjs().format('YYYY')} | Report ID: ${reportId}`,
      105,
      289,
      { align: 'center' }
    );
    
    doc.text(
      `Generated: ${dayjs().format('YYYY-MM-DD HH:mm:ss')}`,
      105,
      293,
      { align: 'center' }
    );
  }

  return doc;
};
