/**
 * Enhanced PDF Report Generator
 * Professional, user-friendly water quality reports
 * 
 * Features:
 * - Professional header/footer with page numbers
 * - Visual status indicators with colors
 * - Summary dashboard section
 * - Better table layouts
 * - Data completeness metrics
 * - Compliance status
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';

interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

interface ReportConfig {
  title: string;
  generatedBy: string;
  deviceIds: string[];
}

/**
 * Add professional header to PDF
 */
function addReportHeader(doc: jsPDF, title: string, reportDate: string): number {
  // Header background
  doc.setFillColor(0, 31, 63); // Navy blue from theme
  doc.rect(0, 0, 210, 50, 'F');
  
  // Logo/Icon placeholder (left side)
  doc.setFillColor(255, 255, 255);
  doc.circle(25, 25, 8, 'F');
  doc.setTextColor(0, 31, 63);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('WQ', 25, 27, { align: 'center' });
  
  // Title (center)
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Water Quality Report', 105, 22, { align: 'center' });
  
  // Subtitle
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 105, 32, { align: 'center' });
  
  // Date (right side)
  doc.setFontSize(9);
  doc.text(reportDate, 185, 25, { align: 'right' });
  
  // Reset colors
  doc.setTextColor(0, 0, 0);
  
  return 55; // Return starting Y position for content
}

/**
 * Add professional footer with page numbers
 */
function addReportFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageHeight = doc.internal.pageSize.height;
  
  // Footer line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, pageHeight - 20, 190, pageHeight - 20);
  
  // Footer text
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'normal');
  doc.text('Water Quality Monitoring System', 20, pageHeight - 12);
  doc.text(`Page ${pageNum} of ${totalPages}`, 190, pageHeight - 12, { align: 'right' });
  doc.text(`Generated: ${dayjs().format('MMM D, YYYY [at] h:mm A')}`, 105, pageHeight - 12, { align: 'center' });
}

/**
 * Add executive summary section
 */
function addExecutiveSummary(
  doc: jsPDF,
  yPos: number,
  reportData: any,
  config: ReportConfig
): number {
  // Section title
  doc.setFillColor(240, 242, 245);
  doc.rect(20, yPos, 170, 10, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 31, 63);
  doc.text('📊 Executive Summary', 25, yPos + 7);
  
  yPos += 15;
  doc.setTextColor(0, 0, 0);
  
  // Summary metrics in a grid
  const summaryData = [
    ['Report Period', reportData.period 
      ? `${dayjs(reportData.period.start).format('MMM D, YYYY')} - ${dayjs(reportData.period.end).format('MMM D, YYYY')}`
      : 'N/A'],
    ['Devices Monitored', `${reportData.devices?.length || 0} devices`],
    ['Total Readings', `${reportData.totalReadings || 0} data points`],
    ['Data Completeness', `${reportData.dataCompleteness || 'N/A'}%`],
    ['Generated By', config.generatedBy],
    ['Report Status', reportData.status || 'Final'],
  ];
  
  autoTable(doc, {
    startY: yPos,
    body: summaryData,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 120 }
    },
    margin: { left: 20 }
  });
  
  return (doc as jsPDFWithAutoTable).lastAutoTable?.finalY! + 10;
}

/**
 * Add compliance status section
 */
function addComplianceStatus(doc: jsPDF, yPos: number, devices: any[]): number {
  // Section title
  doc.setFillColor(240, 242, 245);
  doc.rect(20, yPos, 170, 10, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 31, 63);
  doc.text('✓ Compliance Status', 25, yPos + 7);
  
  yPos += 15;
  doc.setTextColor(0, 0, 0);
  
  // Calculate compliance
  const compliantDevices = devices.filter(d => {
    const m = d.metrics;
    return m && m.avgTurbidity <= 5 && m.avgTDS <= 500 && m.avgPH >= 6.5 && m.avgPH <= 8.5;
  }).length;
  
  const complianceRate = devices.length > 0 ? (compliantDevices / devices.length) * 100 : 0;
  
  // Compliance table
  const complianceData = [
    ['Standard', 'PNSDW/WHO Guidelines'],
    ['Compliant Devices', `${compliantDevices} of ${devices.length}`],
    ['Compliance Rate', `${complianceRate.toFixed(1)}%`],
    ['Overall Status', complianceRate >= 90 ? '✓ COMPLIANT' : complianceRate >= 70 ? '⚠ NEEDS ATTENTION' : '✗ NON-COMPLIANT'],
  ];
  
  autoTable(doc, {
    startY: yPos,
    body: complianceData,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 120 }
    },
    didParseCell: function(data: any) {
      if (data.row.index === 3 && data.column.index === 1) {
        if (complianceRate >= 90) {
          data.cell.styles.textColor = [82, 196, 26]; // Green
          data.cell.styles.fontStyle = 'bold';
        } else if (complianceRate >= 70) {
          data.cell.styles.textColor = [250, 173, 20]; // Orange
          data.cell.styles.fontStyle = 'bold';
        } else {
          data.cell.styles.textColor = [255, 77, 79]; // Red
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
    margin: { left: 20 }
  });
  
  return (doc as jsPDFWithAutoTable).lastAutoTable?.finalY! + 15;
}

/**
 * Add device analysis section with enhanced visuals
 */
function addDeviceAnalysis(
  doc: jsPDF,
  yPos: number,
  device: any,
  deviceNum: number
): number {
  // Check if we need a new page
  if (yPos > 240) {
    doc.addPage();
    yPos = 20;
  }
  
  // Device header
  doc.setFillColor(245, 247, 250);
  doc.rect(20, yPos, 170, 12, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 31, 63);
  doc.text(`Device ${deviceNum}: ${device.deviceName || device.deviceId}`, 25, yPos + 8);
  
  yPos += 17;
  
  // Location info if available
  if (device.location) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`📍 Location: ${device.location}`, 25, yPos);
    yPos += 6;
  }
  
  doc.setTextColor(0, 0, 0);
  
  // Metrics table with visual indicators
  if (device.metrics) {
    const m = device.metrics;
    
    // Helper function to get status
    const getStatus = (param: string, avg: number) => {
      if (param === 'Turbidity') return avg <= 5 ? '✓ GOOD' : '⚠ HIGH';
      if (param === 'TDS') return avg <= 500 ? '✓ GOOD' : '⚠ HIGH';
      if (param === 'pH') return (avg >= 6.5 && avg <= 8.5) ? '✓ GOOD' : '⚠ OUT OF RANGE';
      return 'N/A';
    };
    
    const metricsData = [
      [
        'Turbidity',
        `${m.avgTurbidity?.toFixed(2) || 'N/A'} NTU`,
        `${m.minTurbidity?.toFixed(2) || 'N/A'} / ${m.maxTurbidity?.toFixed(2) || 'N/A'}`,
        '≤ 5 NTU',
        getStatus('Turbidity', m.avgTurbidity || 0)
      ],
      [
        'TDS',
        `${m.avgTDS?.toFixed(2) || 'N/A'} ppm`,
        `${m.minTDS?.toFixed(2) || 'N/A'} / ${m.maxTDS?.toFixed(2) || 'N/A'}`,
        '≤ 500 ppm',
        getStatus('TDS', m.avgTDS || 0)
      ],
      [
        'pH Level',
        m.avgPH?.toFixed(2) || 'N/A',
        `${m.minPH?.toFixed(2) || 'N/A'} / ${m.maxPH?.toFixed(2) || 'N/A'}`,
        '6.5 - 8.5',
        getStatus('pH', m.avgPH || 0)
      ],
    ];
    
    autoTable(doc, {
      startY: yPos,
      head: [['Parameter', 'Average', 'Range (Min/Max)', 'Standard', 'Status']],
      body: metricsData,
      theme: 'striped',
      styles: { 
        fontSize: 8, 
        cellPadding: 4,
        lineColor: [220, 220, 220],
        lineWidth: 0.1
      },
      headStyles: { 
        fillColor: [0, 31, 63], 
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'center'
      },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      columnStyles: {
        0: { cellWidth: 30, fontStyle: 'bold' },
        1: { cellWidth: 30, halign: 'center' },
        2: { cellWidth: 40, halign: 'center' },
        3: { cellWidth: 30, halign: 'center', fontSize: 7 },
        4: { cellWidth: 35, fontStyle: 'bold', halign: 'center' }
      },
      didParseCell: function(data: any) {
        if (data.column.index === 4 && data.section === 'body') {
          const status = data.cell.raw as string;
          if (status.includes('✓')) {
            data.cell.styles.textColor = [82, 196, 26]; // Green
          } else if (status.includes('⚠')) {
            data.cell.styles.textColor = [250, 173, 20]; // Orange
          } else if (status.includes('✗')) {
            data.cell.styles.textColor = [255, 77, 79]; // Red
          }
        }
      },
      margin: { left: 20, right: 20 }
    });
    
    yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY! + 10;
  }
  
  return yPos;
}

/**
 * Main enhanced PDF generation function
 */
export function generateEnhancedWaterQualityReport(config: ReportConfig, reportData: any) {
  const doc = new jsPDF();
  
  // Add header
  let yPos = addReportHeader(
    doc, 
    config.title,
    dayjs().format('MMMM D, YYYY')
  );
  
  // Add executive summary
  yPos = addExecutiveSummary(doc, yPos, reportData, config);
  
  // Add compliance status
  yPos = addComplianceStatus(doc, yPos, reportData.devices || []);
  
  // Add device analysis
  if (reportData.devices && reportData.devices.length > 0) {
    doc.addPage();
    yPos = 20;
    
    // Section title
    doc.setFillColor(240, 242, 245);
    doc.rect(20, yPos, 170, 10, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 31, 63);
    doc.text('📈 Detailed Device Analysis', 25, yPos + 7);
    
    yPos += 15;
    doc.setTextColor(0, 0, 0);
    
    reportData.devices.forEach((device: any, index: number) => {
      yPos = addDeviceAnalysis(doc, yPos, device, index + 1);
    });
  }
  
  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addReportFooter(doc, i, totalPages);
  }
  
  // Save the PDF
  const filename = `Water_Quality_Report_${dayjs().format('YYYY-MM-DD_HHmm')}.pdf`;
  doc.save(filename);
  
  return filename;
}

export default generateEnhancedWaterQualityReport;
